# Generated by Django 5.0.1 on 2024-01-20 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0014_agentgame_customer_agentgametest_customer'),
        ('website', '0002_alter_agent_agent_name_alter_agent_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.agent')),
            ],
        ),
    ]
